apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cifar10-image-classifer
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jetsoncluster.app
    http:
      paths:
      - path: /predict
        backend:
          serviceName: img-classifer-svc
          servicePort: 5000