apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: loggertest
  name: loggertest
spec:
  selector:
    matchLabels:
      app: loggertest
  template:
    metadata:
      labels:
        app: loggertest
    spec:
      containers:
      - image: 108356037/datalogger:arm64helmv1
        name: datalogger
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: BROKER_IP
          value: 'mqtt.paas.oringnet.cloud'

        - name: BROKER_PORT
          value: '1883'

        - name: PUBLISH_TOPIC
          value: '$thing/syjmHv7z-/$data/'

        - name: PUBLISH_PATH
          value: 'sensorData2'

        - name: CLIENT_ID
          value: 'thing:syjmHv7z-'

        - name: USERNAME
          value: 'syjmHv7z-'

        - name: USERPW
          value: 'ZCsC5XNCsk~mzrsy'

        - name: FREQ
          value: '10.0'

        command: ["/bin/bash"]
        args: ["/usr/src/app/entrypoint.sh"]

      nodeSelector:
        kubernetes.io/role: worker
