apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: loggertest
  name: loggertest
spec:
  selector:
    matchLabels:
      app: loggertest
  template:
    metadata:
      labels:
        app: loggertest
    spec:
      containers:
      - image: 108356037/datalogger:arm64datalogger
        name: datalogger
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        # - name: WANT_CUSTOM
        #   value: "True"

        - name: BROKER_IP
          value: "MQTT_BROKER_SVC_PORT_1883_TCP_ADDR"

        - name: BROKER_PORT
          value: "1883"

        - name: PUBLISH_TOPIC
          value: "topic/"

        - name: PUBLISH_PATH
          value: "the/publish/path"

        - name: FREQ
          value: "10.0"

        # command: ["env"]
        command: ["/bin/bash"]
        args: ["/usr/src/app/entrypoint.sh"]

      nodeSelector:
        kubernetes.io/role: worker
