mqtt:
  oringpaas:
    client_id: "thing:syjmHv7z-"
    host: "mqtt.paas.oringnet.cloud"
    port: 1883
    username: "syjmHv7z-"
    userpw: "ZCsC5XNCsk~mzrsy"
    keepalive: 60
    topic: "$thing/syjmHv7z-/$data/"
      # Command: "$thing/syjmHv7z-/$cmd/$downlink/"
      # Downlink config: "$thing/syjmHv7z-/$conf/$expected/"
      # Uplink config: "$thing/syjmHv7z-/$conf/$reported/"
      # Data: "$thing/syjmHv7z-/$data/"
    publish_path: "sensorData"
      # dataBucket: "sensorData"
      # dataShapes: 
      #   - "voltage"
      #   - "cpuTemp"
      #   - "fullDataPackt"
