{{- if .Values.daemonset.sensor_monitor.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
{{- $freq:= .Values.daemonset.sensor_monitor.publish_freq -}}
{{- with .Values.daemonset.sensor_monitor }}
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      nodeSelector: {{ .nodeSelector | toYaml | nindent 8 }}
      containers:
      - image: 108356037/datalogger:arm64helmv1
        name: {{ .name }}
{{- end }}
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        {{- range $key, $val := .Values.rangeParams }}
        - name: {{ $key }}
          value: {{ $val | squote }}
        {{ end }}

        - name: FREQ
          value: {{ $freq | squote }}

        command: ["/bin/bash"]
        args: ["/usr/src/app/entrypoint.sh"]
{{- end }}